### ISSUE TITLE
Using trained models with CPU

### ISSUE THREAD

**Issue by ingo-ch** [facebookresearch/hanabi_SAD#19]
Hello

I don't have access to a GPU and was hoping to use the trained models on a mac cpu. I tried to change the map_location to 'cpu' device in eval_model.py but it won't work. Is there a way to use the trained models with a cpu machine?

**Comment by hengyuan-hu** [comment]
I pushed a patch for evaluation with CPU. Hope it helps.

**Comment by ingo-ch** [comment]
Thank you very much! It works now.
