### ISSUE TITLE
greedy_extra argument

### ISSUE THREAD

**Issue by alexis-jacq** [facebookresearch/hanabi_SAD#2]
Hi, I am trying to catch the difference between VDN and SAD. 

From the paper, I understand that SAD is sharing the same architecture than VDN, but is passed the greedy actions of opponents as inputs for centralized training instead of actual environment actions (case of VDN). 

I deduced that is this code, greedy_extra is the key argument that decides if it will be the VDN or the SAD approach during training. Is this right ?

**Comment by hengyuan-hu** [comment]
Yes you are right.
