### ISSUE TITLE
Support for OBL Training

### ISSUE THREAD

**Issue by 0xJchen** [facebookresearch/hanabi_SAD#22]
Hi, Dr. Hu. I wonder if it is possible to training obl from scratch with the current codes? It seems that only evaluating OBL is supported now. Thanks!

**Comment by hengyuan-hu** [comment]
This repo does not include the OBL code yet. We are working to release the code.

**Comment by mohitahuja1** [comment]
Hi @hengyuan-hu ,

Thanks a lot for your informative answers!

Would you have an approximate estimate on when you would be able to release the OBL code?

Also, have you released the code for the auto-regressive belief model (part of the Learned Belief Search paper) which is used in OBL?

Regards,
Mohit
