### ISSUE TITLE
num_ff_layer 

### ISSUE THREAD

**Issue by KevinJeon** [facebookresearch/hanabi_SAD#23]
Is it right num_ff_layer in R2D2Net instead of 'num_fc_layer'?

**Comment by hengyuan-hu** [comment]
num_ff_layer refers to number of feed-forward layers, which in our case is indeed fully connected layers.

**Comment by hengyuan-hu** [comment]
Ah, now I understand what you mean. Yes, the num_ff_layer in R2D2Net should be changed to num_fc_layer.

**Comment by KevinJeon** [comment]
I uploaded it because I wasn't sure if num_ff_layer was exactly pointing to num_fc_layer during changing the code. Thank you for your answer :)
