### ISSUE TITLE
CMakeFiles/Makefile2:161: recipe for target 'CMakeFiles/hanalearn.dir/all' failed

### ISSUE THREAD

**Issue by hnekoeiq** [facebookresearch/hanabi_SAD#3]
Hi,

When I try to run "make -j10", it gives me this error. 

![Hanabi_Cmake_Error](https://user-images.githubusercontent.com/43013139/73872908-97ba2900-481e-11ea-89cc-aeef0a2ba845.png)

Can you help me realize what is the problem here?

Thanks.

**Comment by hengyuan-hu** [comment]
Hey, unfortunately I cannot reproduce this error. Have you changed the code? What's your compiler version? We have been using gcc-7 for this project. It can also be compiled on Mac using the default compiler, although it will not train properly there due to lack of GPU.

**Comment by hnekoeiq** [comment]
I haven't changed the code and I am using Ubuntu 18.04 which its default gcc version is 7.4.

**Comment by hengyuan-hu** [comment]
Maybe try to comment that part (line153-line155) off and see what will happen? I doubt that is the real cause of the problem. Can you paste the full CMake log here? i.e. the log after you do a clean `cmake ..`
