### ISSUE TITLE
There seems to be a bug in pyhanabi/r2d2.py

### ISSUE THREAD

**Issue by PaladinEE15** [facebookresearch/hanabi_SAD#30]
pyhanabi/r2d2.py", line 69
assert priv_s.dim() == 2, "dim should be 2, [batch, dim], get %d" % s.dim()

s is not defined. Seems that it should be 'priv_s'?

**Comment by hengyuan-hu** [comment]
yes!
Btw, there is a newer and better repo (https://github.com/facebookresearch/off-belief-learning) that implements the algorithms in this repo and more.

**Comment by PaladinEE15** [comment]
Thanks for the reminder! I'll check it out
