### ISSUE TITLE
Why is the last action added twice to the observation?

### ISSUE THREAD

**Issue by ravihammond** [facebookresearch/hanabi_SAD#33]
Hi Hengyuan!

When you encode the observation for a SAD agent, I noticed that the last action is being added twice. It's first added [here](https://github.com/hengyuan-hu/hanabi-learning-environment/blob/273c5ca7f583f178c63693ab58161ca7887f3a89/hanabi_lib/canonical_encoders.cc#L678) when `Encode()` is initially called, and added a second time [here](https://github.com/facebookresearch/hanabi_SAD/blob/415804b531447bb4b8adb12100f994d588589cd8/cpp/hanabi_env.cc#L157) if the `sad_` flag is set.

Why are you adding the last action to the encoding twice? Many thanks in advance for your advice!

**Comment by hengyuan-hu** [comment]
That’s how SAD works, always telling the partner its greedy action even when it is exploring.

**Comment by ravihammond** [comment]
Ah yes, makes sense. Thanks for that!
