### ISSUE TITLE
Where are the other-play equivalence mappings phi actions and observations?

### ISSUE THREAD

**Issue by tessavdheiden** [facebookresearch/hanabi_SAD#34]
Hi Hengyuan,

Could you please indicate where the observation and action mappings are implemented?
These from the paper:
<img width="145" alt="Screenshot 2023-04-04 at 09 07 02" src="https://user-images.githubusercontent.com/24938569/229714685-ca8300d7-d401-43d0-bd01-76dcec72479f.png">

And where they are sampled and applied in an episode?

Many thanks in advance!

Best,
Tessa

**Comment by hengyuan-hu** [comment]
Hi,

It is implemented in
https://github.com/facebookresearch/hanabi_SAD/blob/main/cpp/hanabi_env.cc

Check places with shuffleColor_, colorPermutes_, invColorPermutes_.

Note that there is a better repo “off-belief-learining”. A similar
functionality is implemented in this file of that repo.
https://github.com/facebookresearch/off-belief-learning/blob/main/rlcc/r2d2_actor.cc


Hope it helps!

**Comment by tessavdheiden** [comment]
Hey!

Thanks for the links, I was looking in the Python scripts.

So here you create vectors that permute the actions/moves:

<img width="737" alt="Screenshot 2023-04-05 at 09 45 36" src="https://user-images.githubusercontent.com/24938569/230016826-e3073187-e0c1-4f0b-89f6-b8b21e7962e4.png">

And here is where it is used in the `step()` function:
<img width="556" alt="Screenshot 2023-04-05 at 09 49 13" src="https://user-images.githubusercontent.com/24938569/230017072-5b1b8356-b631-4316-8e8b-28e1fa23c3b1.png">

Where do you permute/map the observations?
Is it true that you first permute the observations, let the player act, and then permute the action back?

Best,
Tessa

**Comment by hengyuan-hu** [comment]
The observation is permuted inside this function `encoder_.Encode`
https://github.com/facebookresearch/hanabi_SAD/blob/415804b531447bb4b8adb12100f994d588589cd8/cpp/hanabi_env.cc#L145


> Is it true that you first permute the observations, let the player act, and then permute the action back?

Yes you are correct!

**Comment by tessavdheiden** [comment]
Hey, Thanks for the help!
