### ISSUE TITLE
ImportError: undefined symbol: _ZNK19hanabi_learning_env10HanabiGame10ParametersEv

### ISSUE THREAD

**Issue by ZishunYu** [facebookresearch/hanabi_SAD#4]
Hi, Hengyuan

I am sorry to bother you but I encounter an import error when I tried to run a trained model.

![image](https://user-images.githubusercontent.com/32248057/73988419-4ab28180-4908-11ea-91a7-dc22027fdabf.png)

I tried to do some search and find some solution but didn't get my issue solved. It seems that the error code is saying that the symbol is undefined in the .so file

But when I do
`nm -g hanalearn.cpython-37m-x86_64-linux-gnu.so | grep _ZNK19hanabi_learning_env10HanabiGame10ParametersEv`
I get
![image](https://user-images.githubusercontent.com/32248057/73988629-dcba8a00-4908-11ea-8b36-fed7571a0892.png)

I am using a different g++ and CUDA version
g++/gcc 5 and CUDA 9.0
same pytorch version (1.3.0)

I understand this might be caused by different g++/gcc version but currently I don't want to upgrade my CUDA (which not compatible with higher g++/gcc). Hence, I am trying to seek some help to fix this without upgrading if possible.

Thank you very much,
ZIshun

**Comment by hengyuan-hu** [comment]
It is highly likely to be a compiler related error. You may try a different compiler and see if you can successfully import the module to decide whether it worth changing the cuda version afterwards.

**Comment by ZishunYu** [comment]
Thanks for your advice. It seems that I have to upgrade CUDA anyway otherwise I cannot compile with GCC/G++ 7.
